Repository SFDO-Community/Summit-Events-App, pull requests merged in 2020-12, with the labels that each got.

#249 Renamed recipient and attributes to allocation for fees
  force-app/main/default/classes/SummitEventsDonationController.cls
  force-app/main/default/classes/SummitEventsRegisterController.cls
  force-app/main/default/classes/SummitEventsSubmitController.cls
  force-app/main/default/layouts/Summit_Events_Fee_Attribute__c-Summit Events Fee Attribute Layout.layout-meta.xml
  force-app/main/default/layouts/Summit_Events_Fee__c-Summit Events Fee Layout.layout-meta.xml
  force-app/main/default/layouts/Summit_Events_Instance__c-Summit Events Instance Default Layout.layout-meta.xml
  force-app/main/default/layouts/Summit_Events_Registration__c-Summit Events Registration Default Layout.layout-meta.xml
  force-app/main/default/layouts/Summit_Events__c-Summit Event Default Layout.layout-meta.xml
  force-app/main/default/objects/Summit_Events_Appointment_Type__c/fields/Appointment_Fee_Additional_Allocation__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Appointment_Type__c/fields/Appointment_Fee_Allocation__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Fee_Allocation__c/Summit_Events_Fee_Allocation__c.object-meta.xml
  force-app/main/default/objects/Summit_Events_Fee_Allocation__c/listViews/All.listView-meta.xml
  force-app/main/default/objects/Summit_Events_Fee_Attribute__c/fields/Banner_Index__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Fee_Attribute__c/fields/FOAPAL__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Fee__c/fields/Event_Fee_Allocation__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Instance__c/fields/Event_Fee_Additional_Allocation_Override__c.field-meta.xml
  force-app/main/default/objects/Summit_Events_Instance__c/fields/Event_Fee_Allocation_Override__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Donation_Allocation_1__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Donation_Allocation_2__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Donation_Allocation_3__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Donation_Allocation_4__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Donation_Allocation_5__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Event_Fee_Additional_Allocation__c.field-meta.xml
  force-app/main/default/objects/Summit_Events__c/fields/Event_Fee_Allocation__c.field-meta.xml
  force-app/main/default/pages/SummitEventsDonation.page
  force-app/main/default/permissionsets/Summit_Events_Admin.permissionset-meta.xml
  force-app/main/default/permissionsets/Summit_Events_Registrant.permissionset-meta.xml
  sfdx-project.json
Labels: bug, package

#253 Add to Calendar Image
  images/Add to Calendar Field Location image.jpg
Labels: documentation

#252 Update SummitEventsAddToCalendarController.cls
  force-app/main/default/classes/SummitEventsAddToCalendarController.cls
Labels: bug
